
from io import BytesIO
from datetime import datetime, date
from reportlab.lib.pagesizes import LETTER
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib import colors

def _header_footer(c, title):
    w, h = LETTER
    c.setFont("Helvetica-Bold", 14)
    c.drawString(0.75*inch, h - 0.75*inch, "TrustLend")
    c.setFont("Helvetica", 9)
    c.drawRightString(w - 0.75*inch, h - 0.6*inch, datetime.utcnow().strftime("Generated %Y-%m-%d %H:%M UTC"))
    c.setStrokeColor(colors.lightgrey)
    c.line(0.75*inch, h - 0.85*inch, w - 0.75*inch, h - 0.85*inch)

    c.setFont("Helvetica-Bold", 12)
    c.drawCentredString(w/2, h - 1.05*inch, title)

    c.setStrokeColor(colors.lightgrey)
    c.line(0.75*inch, 0.9*inch, w - 0.75*inch, 0.9*inch)
    c.setFont("Helvetica", 8)
    c.drawString(0.75*inch, 0.7*inch, "This document was generated by TrustLend PDF Service.")
    c.drawRightString(w - 0.75*inch, 0.7*inch, "Page 1")

def build_contract_pdf(payload: dict) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    _header_footer(c, "Promissory Note & Loan Terms")

    lender = payload["lender"]
    borrower = payload["borrower"]
    loan = payload["loan"]
    tier = payload["tier"]

    x = 0.9*inch
    y = 10.1*inch
    line = 14

    def add(label, value):
        nonlocal y
        c.setFont("Helvetica-Bold", 10); c.drawString(x, y, f"{label}:")
        c.setFont("Helvetica", 10); c.drawString(x+160, y, str(value))
        y -= line

    add("Lender", f'{lender["name"]}  •  {lender["email"]}  •  {lender["phone"]}')
    add("Borrower", f'{borrower["name"]}  •  {borrower["email"]}  •  {borrower["phone"]}')
    add("Principal", f'${loan["principal"]:,.2f}')
    add("Flat Fee", f'${loan.get("flatFee", 0):,.2f}')
    add("Total Owed", f'${(loan["principal"] + loan.get("flatFee", 0)):,.2f}')
    add("Start Date", loan["startDate"])
    add("Term (months)", loan["termMonths"])
    add("Frequency", loan["paymentFrequency"])
    add("Protection Tier", tier)

    y -= 8
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "Key Terms")
    y -= line
    c.setFont("Helvetica", 9)
    terms = [
        "This is a flat-fee loan. No interest is charged; instead, a one-time flat fee applies.",
        "Borrower agrees to repay the Total Owed in equal installments according to the schedule.",
        "Both parties acknowledge and accept electronic records and signatures.",
        "This document may be executed and delivered electronically; copies are binding as originals.",
        "Optional: An Execution Certificate can be appended with verification data (IP, timestamp)."
    ]
    for t in terms:
        c.drawString(x, y, f"• {t}")
        y -= 12

    # Signature blocks
    y -= 10
    c.setFont("Helvetica-Bold", 11)
    c.drawString(x, y, "Signatures"); y -= 18
    c.setFont("Helvetica", 10)
    c.line(x, y, x+250, y); c.drawString(x, y-12, f'Lender: {lender["name"]}     Date: __________')
    y -= 36
    c.line(x, y, x+250, y); c.drawString(x, y-12, f'Borrower: {borrower["name"]}   Date: __________')

    c.showPage()
    c.save()
    return buf.getvalue()

def build_schedule_pdf(payload: dict) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=LETTER)
    _header_footer(c, "Payment Schedule")

    loan = payload["loan"]
    principal = float(loan["principal"])
    flat_fee = float(loan.get("flatFee", 0))
    total = principal + flat_fee
    months = int(loan["termMonths"])
    per_payment = total / months if months else total

    x0 = 0.8*inch
    y = 10.5*inch

    headers = ["#","Due Date","Payment","To Principal","To Fee","Balance"]
    widths = [30, 120, 90, 100, 80, 100]

    c.setFont("Helvetica-Bold", 10)
    x = x0
    for h, w in zip(headers, widths):
        c.drawString(x, y, h)
        x += w
    y -= 14
    c.setStrokeColor(colors.black)
    c.line(x0, y, x0 + sum(widths), y)
    y -= 10

    c.setFont("Helvetica", 9)
    from datetime import datetime
    from dateutil.relativedelta import relativedelta  # not in requirements to keep light; replace simple calc
    # To avoid dependency, implement simple month add:
    def add_months(dt, n):
        y, m = dt.year, dt.month + n
        y += (m-1)//12
        m = (m-1)%12 + 1
        d = min(dt.day, [31,29 if (y%4==0 and (y%100!=0 or y%400==0)) else 28,31,30,31,30,31,31,30,31,30,31][m-1])
        return dt.replace(year=y, month=m, day=d)

    start = datetime.strptime(loan["startDate"], "%Y-%m-%d").date()
    balance = total
    remaining_fee = flat_fee

    for i in range(1, months+1):
        due = add_months(start, i)
        pay = round(per_payment, 2)
        # allocate fee first until exhausted, then principal
        to_fee = min(remaining_fee, pay)
        to_principal = pay - to_fee
        remaining_fee -= to_fee
        balance = round(balance - pay, 2)

        x = x0
        row = [str(i), due.strftime("%Y-%m-%d"),
               f"${pay:,.2f}", f"${to_principal:,.2f}", f"${to_fee:,.2f}", f"${max(balance,0):,.2f}"]
        for cell, w in zip(row, widths):
            c.drawString(x, y, cell)
            x += w
        y -= 12
        if y < 1.2*inch:
            c.showPage()
            _header_footer(c, "Payment Schedule (cont.)")
            y = 10.5*inch
            c.setFont("Helvetica", 9)

    c.showPage()
    c.save()
    return buf.getvalue()
